language: java
jdk:
  - oraclejdk8
install: true

script:
  - mvn clean verify -Pproduct -Dtycho.localArtifacts=ignore -Declipse.p2.mirrors=false

# safelist
branches:
  only:
  - master
  - develop

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  draft: true
  api_key:
    secure: BkqAzl+bn6o58IvnBn/VW53oPSar7bsHZ4NiazlfJCla1oThisVpkwYQFjlVZzHQY6gOzb9Nbfp412C/FNz+J1Pelaim8qVgnh33VKJXT9E/KJLU+3wYJkhHTmBTv2YhSrbB9HQmLOoPWlNrd4drOOOhdSyRxXiwVW+girPsfUKz7PkcSNkGuJ26PavzWifYWK6Ub8cdqtukuK5tj872lX13K8fK/CYwjS0ncG3ELIdo2Zt6cdqSlbpRfZZUp37P2WUFwgLikoWiG9t/6KBqHwYAXGDHUoBxFC2sPQE7OCE4/EEhMDUkhCZEz7XUh/BQV+2m7k/VNrIEuuJNHV1WZmv63WG/CcrfHz6aTub7C7uQyhT1runiszh85Mrq9eaKWugh5Oq62e36gZUDsXCKiGY3CUTSZUzgR+CDVB3T7JbFS81105djgA1VFFWJ/IZ+VZOwL//ju/XQ0R5wC1peEAiV+ZI5RSY8sEJ/QcNAA9FA3zf2abTmxL7foRq7gf3rgNYaqn0xZNiXn8UvSn8tiMpGqaoHFGXLqikRtCGXqOquHPyTMmMMclH7iyv/AzWLPq3i5aY9MXxksbSjYH16P+PvP2SzDcYF+cGFVyLXUkT28q6r8yiXElnJ4e2+rzuRwfuFaV/bRu9kSHWRnM1pbhBXru9Y+fTy4FvgqhEytVo=
  file: 
  - releng/com.zeligsoft.po.posysml.product/target/products/com.zeligsoft.po.posysml.product-win32.win32.x86_64.zip
  - releng/com.zeligsoft.po.posysml.product/target/products/com.zeligsoft.po.posysml.product-linux.gtk.x86_64.zip
  - releng/com.zeligsoft.po.posysml.product/target/products/com.zeligsoft.po.posysml.product-macosx.cocoa.x86_64.tar.gz
  on:
    repo: eclipsesource/po-presto
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$
    
